### ISSUE TITLE
Docker Compose | Environment variables as config

### ISSUE THREAD

**Issue by ToshY** [casdoor/casdoor#1065]
Hello 👋 

I'm using casdoor `v1.103.0` with docker compose, and I want to pass the environment variables from the [docs](https://casdoor.org/docs/basic/server-installation#via-ini-file) to the container.

Example:

```yaml
version: '3.9'

services:
  casdoor:
    image: casbin/casdoor:${CASDOOR_IMAGE_VERSION}
    restart: 'no'
    entrypoint: /bin/sh -c './server --createDatabase=true'
    environment:
      RUNNING_IN_DOCKER: "true"
      APPNAME: ${CASDOOR_APP_NAME}
      HTTPPORT: ${CASDOOR_HTTP_PORT}
      RUNMODE: ${CASDOOR_RUN_MODE}
      SESSIONON: ${CASDOOR_SESSION_ON}
      COPYREQUESTBODY: ${CASDOOR_COPY_REQUEST_BODY}
      DRIVERNAME: ${DATABASE_HOST}
      DATASOURCENAME: ${DATABASE_USER}:${DATABASE_USER_PASSWORD}@tcp(${DATABASE_HOST}:${DATABASE_PORT})/
      DBNAME: ${DATABASE_NAME}
      TABLENAMEPREFIX: ${CASDOOR_TABLE_NAME_PREFIX}
      SHOWSQL: ${CASDOOR_SHOW_SQL}
      REDISENDPOINT: ${CASDOOR_REDIS_ENDPOINT}
      DEFAULTSTORAGEPROVIDER: ${CASDOOR_DEFAULT_STORAGE_PROVIDER}
      ISCLOUDINTRANET: ${CASDOOR_IS_CLOUD_INTRANET}
      AUTHSTATE: ${CASDOOR_AUTH_STATE}
      SOCKS5PROXY: ${CASDOOR_SOCKS5_PROXY}
      VERIFICATIONCODETIMEOUT: ${CASDOOR_VERIFICATION_CODE_TIMEOUT}
      INITSCORE: ${CASDOOR_INIT_SCORE}
      LOGPOSTONLY: ${CASDOOR_LOG_POST_ONLY}
      ORIGIN: ${CASDOOR_ORIGIN}
      STATICBASEURL: ${CASDOOR_STATIC_BASE_URL}
    depends_on:
      - mysql
```

It is possible to make this feature?

Thanks in advance.

**Comment by hsluoyz** [comment]
@ToshY see: https://casdoor.org/docs/basic/server-installation#via-environment-variables

**Comment by ToshY** [comment]
@hsluoyz 

> @ToshY see: https://casdoor.org/docs/basic/server-installation#via-environment-variables

Please reopen this issue, as this as the documentation does **not** explain how to pass environment variables with docker compose. And looking at the `docker-entrypoint.sh` it does not seem possible right now. Here's an [example](https://github.com/databacker/mysql-backup/blob/master/entrypoint) of a `docker-entrypoint.sh` passing environment variables with `file_env`.

**Comment by hsluoyz** [comment]
@ToshY I think it's more of a Docker usage issue?

@ComradeProgrammer

**Comment by ToshY** [comment]
@hsluoyz It is a feature request, not an issue. It's a common container practice to use environment variables instead of config files, as you generally do not want to expose secrets (like database or Redis DSN). It currently seems it is not possible to pass environment variables like my example above, therefor I was asking if this feature could be made.

**Comment by hsluoyz** [comment]
@ToshY it's about how to add environment variable inside a Docker container, this question is not related to Casdoor directly. I mean anyone can face such a problem in any software inside a Docker container.

**Comment by ToshY** [comment]
How is this not related to Casdoor?  [Casbin/casdoor](https://hub.docker.com/r/casbin/casdoor) is your repository on Dockerhub right? I'm using that image, and I'm simply making a feature request to pass environment variables instead of a config file. The majority of popular software support this practice so I just wanted to know if this is going to be supported for the Casdoor docker image as well.

**Comment by hsluoyz** [comment]
@ToshY can you make a PR to support it?

**Comment by SidneySun** [comment]
Hi @ToshY, I'm using docker-compose and following this [documentation](https://casdoor.org/docs/basic/server-installation#via-environment-variables) successfully passed environment variables. 
> The names of environmental variables should be exactly the same with the names you want to use in the ini file.

Are your variable names exactly the same as those used in the ini file? 
```
    environment:
      - appname=casdoor
      - httpport=8000
```

**Comment by ToshY** [comment]
Hello @SidneySun 

Apparently not, as I have them uppercased. I didn't read it to the letter, so apologies to @hsluoyz.

_However_, this does not take away that it breaks the [convention for naming environment variables](https://google.github.io/styleguide/shellguide.html#s7.3-constants-and-environment-variable-names). Currently, the variables defined in the config use **3** different naming conventions: lowercase, camelCase and PascalCase. And then there is the `RUNNING_IN_DOCKER` environment variable which seems to be correctly in upper snake case. So in total you would have **4** different types of naming conventions for the environment variables then. I have not yet used or seen such inconsistent usage of environment variable naming in a docker image/application yet.

@SidneySun Would you mind to share your `docker-compose.yml`?

**Comment by hsluoyz** [comment]
@ToshY Thanks for pointing out the naming issue. I can explain it.

1. Beego built-in var names are lowercase and cannot be changed easily:

https://github.com/casdoor/casdoor/blob/411d76798d73446fff4a0244f0475f1ea8bf42dc/conf/app.conf#L1-L4

2. We (Casdoor) prefer camelCase:

https://github.com/casdoor/casdoor/blob/411d76798d73446fff4a0244f0475f1ea8bf42dc/conf/app.conf#L5-L19

3. About PascalCase, can you give me some pointers? I didn't find them.

4. About `RUNNING_IN_DOCKER`, we will change it to `runningInDocker`

Finally, it would be ideal if we have `lowercase` and `camelCase` co-existing.

**Comment by SidneySun** [comment]
```
version: '3.1'
services:
  casdoor:
    image: casbin/casdoor:v1.103.0
    networks:
      - casdoor
    ports:
      - "8000:8000"
    # entrypoint: /bin/sh -c './server --createDatabase=true'
    environment:
      - RUNNING_IN_DOCKER=true
      - appname=casdoor
      - httpport=8000
      - runmode=dev
      - copyrequestbody=true
      - driverName=mysql
      - dataSourceName=casdoor:abc@tcp(casdoor_db:3306)/
      - dbName=casdoor
        # - tableNamePrefix=
      - showSql=false
      - redisEndpoint=
        # - defaultStorageProvider=
      - isCloudIntranet=false
      - authState=casdoor
      - socks5Proxy=127.0.0.1:10808
      - verificationCodeTimeout=10
      - initScore=2000
      - logPostOnly=true
        # - origin=
      - staticBaseUrl="https://cdn.casbin.org"
    depends_on:
      - casdoor_db
    restart: unless-stopped
  casdoor_db:
    image: mysql:8.0.30
    networks:
      - casdoor
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=casdoor
      - MYSQL_USER=casdoor
      - MYSQL_PASSWORD=abc
      - MYSQL_ROOT_PASSWORD=cba
    volumes:
      - ./var/db:/var/lib/mysql
    restart: unless-stopped

networks:
  casdoor:
```
I also only used Casdoor for a few hours. Welcome to continue to communicate. The casdoor service will keep restarting until mysql is initialized. You can change the version of docker-compose.yml to 3.8 and use health check, but it's not necessary for me at the moment.
