### ISSUE TITLE
panic: Unsupported driver name (K8s) minikube

### ISSUE THREAD

**Issue by GmBeHappy** [casdoor/casdoor#1278]
I've tried to deploy casdoor to minikube by using default k8s.yml in repo and I got this error.
Can anyone help me to fix this.

Error:
```
panic: Unsupported driver name: 

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Adapter).open(0xc000206e80)
	/go/src/casdoor/object/adapter.go:107 +0xb2
github.com/casdoor/casdoor/object.NewAdapter({0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0})
	/go/src/casdoor/object/adapter.go:80 +0xd0
github.com/casdoor/casdoor/object.InitAdapter(0x0)
	/go/src/casdoor/object/adapter.go:49 +0x76
main.main()
	/go/src/casdoor/main.go:38 +0xa7
```

I'm also trying to build a casdoor image locally on my server and have the same error.

I'm new in k8s. if anyone has advice please tell me.

Thank you.

**Comment by GmBeHappy** [comment]
This is app.conf file

```
appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = mysql
dataSourceName = root:xxx@tcp(localhost:3306)/
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider = 
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
ldapServerPort = 389
languages = en,zh,es,fr,de,ja,ko,ru
```

I think I forgot to deploy MySQL. 😅
I'm trying Thank you.

**Comment by GmBeHappy** [comment]
@hsluoyz 
I deployed MySQL but still have the same error.

I think it has a problem with the mapping column. 
Can you check my latest k8s.yml?

k8s.yml:
```yml
apiVersion: v1
kind: Service
metadata:
  namespace: casdoor
  name: casdoor-svc
  labels:
    app: casdoor
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    app: casdoor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: casdoor
  name: casdoor-deployment
  labels:
    app: casdoor
spec:
  #EDIT IT: if you don't use redis, casdoor should not have multiple replicas
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor-container
          image: casbin/casdoor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: conf
              mountPath: /conf
          env:       
            - name: RUNNING_IN_DOCKER
              value: "true"
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: casdoor-config-pvc
```

PV : 
```yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: casdoor-pv
  namespace: casdoor
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/gm/casdoor/casdoor/conf
  persistentVolumeReclaimPolicy: Retain
```

PVC :
```yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casdoor-config-pvc
  namespace: casdoor
  labels:
    app: casdoor
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
```


Thank you very much.

**Comment by Abingcbc** [comment]
@GmBeHappy Could you enter the pod to see if the conf file is mounted correctly?
You can use commands like `kubectl exec -it <pod name> sh`

**Comment by GmBeHappy** [comment]
@Abingcbc I can't exec to pod because pod cannot start.
This is the error I got.

<img width="937" alt="Screenshot 2565-11-09 at 16 25 44" src="https://user-images.githubusercontent.com/35629716/200792020-c4da3647-2e8e-48fb-a5ca-02a75564536a.png">

**Comment by Abingcbc** [comment]
@GmBeHappy Could you reproduce the error stably? I cannot reproduce this error with your app.conf and yaml.
Here is my test files and they are almost same with yours.
```
apiVersion: v1
kind: Namespace
metadata:
  name: casdoor
  annotations:
  labels:
    name: casdoor
---
apiVersion: v1
kind: Service
metadata:
  namespace: casdoor
  name: casdoor-svc
  labels:
    app: casdoor
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    app: casdoor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: casdoor
  name: casdoor-deployment
  labels:
    app: casdoor
spec:
  #EDIT IT: if you don't use redis, casdoor should not have multiple replicas
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor-container
          image: casbin/casdoor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: conf
              mountPath: /conf
          env:       
            - name: RUNNING_IN_DOCKER
              value: "true"
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: casdoor-config-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: casdoor-pv
  namespace: casdoor
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/ubuntu/conf
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casdoor-config-pvc
  namespace: casdoor
  labels:
    app: casdoor
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
```

Put this file in your PV hostpath and name it as `app.conf`

```
appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = mysql
dataSourceName = root:xxx@tcp(localhost:3306)/
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider = 
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
ldapServerPort = 389
languages = en,zh,es,fr,de,ja,ko,ru
```
