### ISSUE TITLE
Handler crashed with error http: wrote more than the declared Content-Length

### ISSUE THREAD

**Issue by SidneySun** [casdoor/casdoor#1788]
I use this docker-compose.yml
```
version: '3.1'
services:
  casdoor:
    image: casbin/casdoor:v1.299.0
    networks:
      - casdoor
    ports:
      - 8000:8000
    # entrypoint: /bin/sh -c './server --createDatabase=true'
    environment:
      - RUNNING_IN_DOCKER=true
      - appname=casdoor
      - httpport=8000
      - runmode=dev # modify
      - copyrequestbody=true
      - driverName=postgres
      - dataSourceName=user=casdoor password=xxx host=casdoor_db port=5432 sslmode=disable dbname=casdoor
      - dbName=
      - tableNamePrefix=
      - showSql=false
      - redisEndpoint=
      - defaultStorageProvider=
      - isCloudIntranet=false
      - authState=casdoor
      - socks5Proxy=127.0.0.1:10808
      - verificationCodeTimeout=10
      - initScore=2000
      - logPostOnly=true
      - origin=
      - staticBaseUrl="https://cdn.casbin.org"
    depends_on:
      - casdoor_db
    restart: unless-stopped

  casdoor_db:
    image: postgres:14.3-alpine
    networks:
      - casdoor
    environment:
      - POSTGRES_USER=casdoor
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_DB=casdoor
    expose:
      - 5432
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  casdoor:
```
After I visit http://localhost:8000, I get a blank webpage and this error:
```
casdoor-casdoor-1     | panic: dial tcp 172.24.0.2:5432: connect: connection refused
casdoor-casdoor-1     |
casdoor-casdoor-1     | goroutine 1 [running]:
casdoor-casdoor-1     | github.com/casdoor/casdoor/object.(*Adapter).createTable(0xc0007ec7c0)
casdoor-casdoor-1     |         /go/src/casdoor/object/adapter.go:131 +0x9ee
casdoor-casdoor-1     | github.com/casdoor/casdoor/object.CreateTables(0x20)
casdoor-casdoor-1     |         /go/src/casdoor/object/adapter.go:56 +0x31
casdoor-casdoor-1     | main.main()
casdoor-casdoor-1     |         /go/src/casdoor/main.go:40 +0xb2
casdoor-casdoor-1     | panic: dial tcp 172.24.0.2:5432: connect: connection refused
casdoor-casdoor-1     |
casdoor-casdoor-1     | goroutine 1 [running]:
casdoor-casdoor-1     | github.com/casdoor/casdoor/object.(*Adapter).createTable(0xc00080e7c0)
casdoor-casdoor-1     |         /go/src/casdoor/object/adapter.go:131 +0x9ee
casdoor-casdoor-1     | github.com/casdoor/casdoor/object.CreateTables(0x20)
casdoor-casdoor-1     |         /go/src/casdoor/object/adapter.go:56 +0x31
casdoor-casdoor-1     | main.main()
casdoor-casdoor-1     |         /go/src/casdoor/main.go:40 +0xb2
casdoor-casdoor-1     | [xorm] [warn]  2023/04/25 15:51:05.870611 Table permission_rule has column id but struct has not related field
casdoor-casdoor-1     | [xorm] [warn]  2023/04/25 15:51:05.943016 Table permission_rule has column id but struct has not related field
casdoor-casdoor-1     | 2023/04/25 15:51:10 Listening on 0.0.0.0:389
casdoor-casdoor-1     | 2023/04/25 15:51:10.135 [I]  http server Running on http://:8000
casdoor-casdoor-1     | 2023/04/25 15:51:23.359 [C]  the request url is  /
casdoor-casdoor-1     | 2023/04/25 15:51:23.359 [C]  Handler crashed with error http: request method or response status code does not allow body
casdoor-casdoor-1     | 2023/04/25 15:51:23.359 [C]  /usr/local/go/src/runtime/panic.go:1038
casdoor-casdoor-1     | 2023/04/25 15:51:23.359 [C]  /go/src/casdoor/routers/static_filter.go:83
casdoor-casdoor-1     | 2023/04/25 15:51:23.359 [C]  /go/src/casdoor/routers/static_filter.go:61
casdoor-casdoor-1     | 2023/04/25 15:51:23.359 [C]  /go/pkg/mod/github.com/beego/beego@v1.12.11/router.go:678
casdoor-casdoor-1     | 2023/04/25 15:51:23.359 [C]  /go/pkg/mod/github.com/beego/beego@v1.12.11/router.go:771
casdoor-casdoor-1     | 2023/04/25 15:51:23.360 [C]  /usr/local/go/src/net/http/server.go:2879
casdoor-casdoor-1     | 2023/04/25 15:51:23.360 [C]  /usr/local/go/src/net/http/server.go:1930
casdoor-casdoor-1     | 2023/04/25 15:51:23.360 [C]  /usr/local/go/src/runtime/asm_amd64.s:1581
```
Does anyone have encountered the same problem? Thanks!
