### ISSUE TITLE
Docker: Images not available

### ISSUE THREAD

**Issue by pluja** [casdoor/casdoor#1896]
I have tried to setup Casdoor with docker, but all images seem to be missing. Here's my compose file:

```
version: '3.9'
services:
    casdoor:
      image: casbin/casdoor:latest
      volumes:
        - ./config:/conf
      environment:
        RUNNING_IN_DOCKER: "true"
      depends_on:
        - database
      networks:
        - default
        - caddy
      labels:
        caddy: door.mydomain.com
        caddy.reverse_proxy: "{{upstreams 8000}}"
    
    database:
      image: mariadb:latest
      environment:
        MARIADB_DATABASE: casdoor
        MARIADB_USER: casdoor
        MARIADB_PASSWORD: DatabasePassword
        MARIADB_RANDOM_ROOT_PASSWORD: true
      volumes:
        - ./database:/var/lib/mysql

networks:
  caddy:
    external: true
```

And my `app.conf`:

```
appname = casdoor
httpport = 8000
runmode = prod
copyrequestbody = true
driverName = mysql
dataSourceName = casdoor:DatabasePassword@tcp(database:3306)/
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
Domain = https://door.mydomain.com/images
defaultStorageProvider = https://door.mydomain.com/images
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin =
staticBaseUrl = "https://door.mydomain.com"
isDemoMode = false
batchSize = 100
ldapServerPort = 389
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
```

The database connection and everything is correct. I can access the UI, but simply all images are broken:

![](https://i.imgur.com/kjDn7FK.png)

Is there anything I'm doing wrong?
