### ISSUE TITLE
casdoor startup error with postgresql

### ISSUE THREAD

**Issue by stilet** [casdoor/casdoor#2127]
At startup the following error:
```
casdoor       | panic: pq: syntax error at or near ";"
casdoor       | 
casdoor       | goroutine 1 [running]:
casdoor       | github.com/casdoor/casdoor/object.InitAdapter()
casdoor       |         /go/src/casdoor/object/adapter.go:53 +0x1e6
casdoor       | main.main()
casdoor       |         /go/src/casdoor/main.go:42 +0x34
```
```
docker-compose:
  casdoor:
    restart: always
    networks:
      - default
    image: 'casbin/casdoor:latest'
    container_name: casdoor
    env_file:
      - .casdoor
    environment:
      RUNNING_IN_DOCKER: "true"  
    depends_on:
      - db_casdoor
    ports:
      - 9080:8000

  db_casdoor:
    image: postgres:bullseye
    container_name: db_casdoor
    env_file:
      - .casdoor
    working_dir: /
    volumes:
      - db-volume-casdoor:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - default
```
.casdoor:

```
POSTGRES_PASSWORD=xxxxxxx
POSTGRES_USER=casdoorxxx
POSTGRES_DB=casdoor
appname=casdoor
httpport=8000
runmode=dev
SessionOn=true
copyrequestbody=true
driverName=postgres
dataSourceName="user=casdoorxxx password=xxxxxxx host=db_casdoor port=5432 sslmode=disable dbname=casdoor"
dbName=
tableNamePrefix=
showSql=false
redisEndpoint=
defaultStorageProvider=
isCloudIntranet=false
authState="casdoor"
socks5Proxy="127.0.0.1:10808"
verificationCodeTimeout=10
initScore=2000
logPostOnly=true
origin="https://auth.xxxxx.com"
staticBaseUrl="https://cdn.casbin.org"
enableGzip=true
```
