### ISSUE TITLE
nextauth integration and openid-configuration 

### ISSUE THREAD

**Issue by yescine** [casdoor/casdoor#2328]
I want to integrate Casdoor in NextJs project with library [nextauth ](https://next-auth.js.org/configuration/providers/oauth#using-a-custom-provider) as custom provider

I' am using casdoor in docker-compose with the following setup:

```yaml
version: "3.1"
services:
  casdoor:
    image: casbin/casdoor:v1.407.0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      # RUNNING_IN_DOCKER: "true"
      driverName: postgres
      dataSourceName: user=postgres host=postgres port=5432 password=postgrespassword sslmode=disable dbname=casdoor
      dbName: casdoor
    volumes:
      - ./conf:/conf/
  postgres:
    image: postgres:15 #tested with 12 & 15 ,13 need wait time
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: casdoor
    ports:
      - "5432:5432"
    volumes:
      - postgresDB:/var/lib/postgresql

volumes:
  postgresDB:
```

and my [...auth].ts

```js
import NextAuth, { AuthOptions } from "next-auth";

export const authOptions: AuthOptions = {
  providers: [
    {
      id:"casdoor",
      name: "Casdoor",
      type: "oauth",
      clientId:"3cae40b7e1f4af89a461",
      clientSecret:"efea20d546b4f6be5b8dd974dc9ba5ad686586e6",
      issuer:"http://localhost:8000",
      wellKnown:"http://localhost:8000/.well-known/openid-configuration",
      profile(profile) {
        return {
          id: profile.id,
          name: profile.name,
          email: profile.email,
        }
      },
    }
  ],
};

export default NextAuth(authOptions);
```
in `/.well-known/openid-configuration` I get Different `authorization_endpoint` url port (here 7001) 

![image](https://github.com/casdoor/casdoor/assets/63535911/a6f14ff3-65e3-4097-9a16-d1bc5aeb72a9)

It should be the same as the url and port of the Dashboard ! 
**Is there a way to change it** ?
