### ISSUE TITLE
Bug: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by jerlendds** [casdoor/casdoor#2461]
I'm not entirely sure what I'm doing as it's my first time using Casdoor, perhaps errors passthrough like this since its not configured for production and I'm `GET`ing the API endpoint incorrectly? I'm looking for some clarification on how to add applications, organizations, and users to an instance through the `init_data.json`. Here's what's happening:

When using the compose service located at the very bottom for running Casdoor I run into a runtime error returned as HTML by the Casdoor public API when trying to get an application:

1.) To create the values for init_data I used the UI and created my org, app, cert, and user
1.5) I'm able to authenticate through my frontend React app with the previously created information. I want to now get those values through the public API so I can populate my `init_data.json`. 
2.) I grab my access_token that I can use to authenticate with the frontend and navigate to the swagger docs to call the [localhost:45910/api/get-application?id=](http://localhost:45910/api/get-application?id=) endpoint but I run into a CORs issue and I wasn't able to find docs on how to configure the origins. 
3.) If I manually call the API through my Insomnia client or from my backend with Python requests I run into the following runtime error
```casdoor:runtime error: index out of range [1] with length 1

Request Method:	GET
Request URL:	/api/get-user?id=app-built-in
RemoteAddr:	192.168.32.1
Stack
/usr/local/go/src/runtime/panic.go:884
/usr/local/go/src/runtime/panic.go:113
/go/src/casdoor/util/string.go:123
/go/src/casdoor/routers/authz_filter.go:79
/go/src/casdoor/routers/authz_filter.go:177
/go/pkg/mod/github.com/beego/beego@v1.12.12/router.go:678
/go/pkg/mod/github.com/beego/beego@v1.12.12/router.go:771
/usr/local/go/src/net/http/server.go:2947
/usr/local/go/src/net/http/server.go:1991
/usr/local/go/src/runtime/asm_amd64.s:1594
beego 1.12.3 (beego framework)

golang version: go1.19.9
```
![image](https://github.com/casdoor/casdoor/assets/29207058/85129e9e-9de2-4f25-b1e5-dc6af639b6e3)

**Docker compose service:**
*Source: github.com/jerlendds/osintbuddy/blob/develop/ob/alpha-compose.yml*
```yml
  casdoor:
    image: casbin/casdoor:latest
    restart: on-failure
    ports:
      - 45910:45910
    volumes:
      - ./_casdoor/conf:/conf
     # - ./_casdoor/init_data.json:/init_data.json
 db:
    image: "${POSTGRES_IMAGE-postgres:15.4}"
    volumes:
      - "ob-db-data:${PGDATA-/var/lib/postgresql/data/pgdata}"
    env_file:
      - .env.alpha
    ports:
      - "${POSTGRES_PORT-55432}:5432"
```
 
 **conf/app.conf**
      
```conf
 appname = casdoor
httpport = 45910
runmode = dev
copyrequestbody = true
driverName = postgres
dataSourceName ="user=casdoor password=casdoorpassword host=db port=5432 sslmode=disable dbname=casdoor"
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
origin =
originFrontend =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
enableGzip = true
ldapServerPort = 389
radiusServerPort = 1812
radiusSecret = "secret"
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
logConfig = {"filename": "logs/casdoor.log", "maxdays":99999, "perm":"0770"}
initDataFile = "./init_data.json"
frontendBaseDir = "../casdoor"
 ```
 
 Any chance someone knows if I'm missing something in the docs? I'm looking forward to being able to use Casdoor, just need to figure this out first. Overall though, looks like a great project, thanks for all the work
