### ISSUE TITLE
Can‘t use the Local File System provider to store uploaded files

### ISSUE THREAD

**Issue by seeleclover** [casdoor/casdoor#2987]
### Bugs:

I use **Docker** to deploy Casdoor. After I started the container and added the Local File System provider to the casdoor, I encountered the following errors when uploading resources or avatar images:

> Casdoor fails to create folder: "/files/resource/built-in/admin" for local file system storage provider: mkdir /files/resource: permission denied. Make sure Casdoor process has correct permission to create/access it, or you can create it manually in advance

![screenshot](https://github.com/casdoor/casdoor/assets/37256067/ce3eef8e-92be-4646-9cc9-2a4346376253)

### Solution:

Later, I found a solution to this problem:  
1. Enter the container  to create `/files` directory  
2. Assign 766 permissions to `/files` directory  
3. Modify the user and group to `casdoor` for `/files` directory  

Considering that a considerable number of users still use the Local File System provider for casdoors, can these operations be written into Dockerfile to build images? For example:

```Dockerfile
RUN mkdir -p /files \
    && chmod -R 766 /files \
    && chown casdoor:casdoor /files
```

**Comment by dacongda** [comment]
mount /files dir to the host system manually may be a better solution

**Comment by QYG2297248353** [comment]
I'm still getting this problem, trying to give permission to the mount directory 1000:1000 still fails

`chown -R 1000:1000 /home/data/casdoor/`

Hub build, because the specified USER is 1000

![image](https://github.com/user-attachments/assets/f0803354-6762-4f3b-a347-2723e2bda656)


```yml
networks:
    1panel-network:
        external: true
services:
    casdoor:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        env_file:
            - /etc/1panel/envs/global.env
            - /etc/1panel/envs/casdoor/casdoor.env
            - ${ENV_FILE:-/etc/1panel/envs/default.env}
        environment:
            - driverName=${DB_TYPE}
            - dbName=${DB_NAME}
            - verificationCodeTimeout=10
            - appname=casdoor
            - authState=casdoor
        image: casbin/casdoor:v1.646.0
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:8000
        restart: always
        volumes:
            - ${CASDOOR_ROOT_PATH}/data/files:/home/user/casdoor/files
version: "3.8"
```
where `CASDOOR _ ROOT _ PATH=/home/data/casdoor`

![image](https://github.com/user-attachments/assets/919481db-5222-498b-8c8a-af9f7f5b722d)
