### ISSUE TITLE
Cannot read properties of null at Object.isPasswordEnabled after upgrading

### ISSUE THREAD

**Issue by SidneySun** [casdoor/casdoor#3073]
After I upgraded to v1.649.0 or v1.490.0 from v1.465.0, I got an error in the web console: 
```TypeError: Cannot read properties of null (reading 'filter')
    at Object.isPasswordEnabled (Setting.js:1136:38)
    at r.value (LoginPage.js:1056:43)
    at ks (react-dom.production.min.js:204:189)
    at Cs (react-dom.production.min.js:203:149)
    at wl (react-dom.production.min.js:292:172)
    at gc (react-dom.production.min.js:280:389)
    at fc (react-dom.production.min.js:280:320)
    at hc (react-dom.production.min.js:280:180)
    at nc (react-dom.production.min.js:271:88)
    at tc (react-dom.production.min.js:268:429)
```

The signinMethods may be null in #2566 if upgrading from an older version.

**Comment by dacongda** [comment]
I fail to reporduce this bug .
I try to 
- pull casbin/casdoor:v1.465.0 image from dockerhub  
- create a completely blank database
- change database link in app.conf 
- try to login and success
- pull casbin/casdoor:latest image from dockerhub and use raw app.conf to start
- try to login and get a clean console without any error
can you tell me what database did you using and have you change anything of casdoor?

**Comment by SidneySun** [comment]
I can reproduce.
Run a new container.
```
version: '3.1'
services:
  casdoor:
    image: casbin/casdoor:v1.465.0
    networks:
      - casdoor
    ports:
      - 8080:8000
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      - ./etc/app.conf:/conf/app.conf:ro
    depends_on:
      - casdoor_db
    restart: unless-stopped

  casdoor_db:
    image: postgres:14.3-alpine
    networks:
      - casdoor
    environment:
      - POSTGRES_USER=casdoor
      - POSTGRES_PASSWORD=simple_password
      - POSTGRES_DB=casdoor
    expose:
      - 5432
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  casdoor:
```
```
appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName= postgres
dataSourceName= "user=casdoor password=simple_password host=casdoor_db port=5432 sslmode=disable dbname=casdoor"
dbName =
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
ldapServerPort = 389
languages = en,zh
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
```

Create a new default organization.
Create a new default user in the new organization.
Stop the container and upgrade to v1.649.0 or v 1.490.0 .
Open http://localhost:8080/login/built-in
