### ISSUE TITLE
Failed to sign in: unexpected end of JSON input

### ISSUE THREAD

**Issue by ybizeul** [casdoor/casdoor#3224]
Deployed Casdoor in kubernetes, when logging in with `admin` / `123` or `built-in\admin` / `123` I get 

```
Failed to sign in: unexpected end of JSON input
```

Here is my deployment :
```
# this is only an EXAMPLE of deploying casddor in kubernetes
# please modify this file according to your requirements
apiVersion: v1
kind: Namespace
metadata:
  name: casdoor
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: casdoor
  namespace: casdoor
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: auth-dev.mydomain.org
    traefik.ingress.kubernetes.io/router.tls.domains.0.sans: auth-dev.mydomainorg
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - auth-dev.mydomain.org
  rules:
    - host: auth-dev.mydomain.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: casdoor
                port:
                  number: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: casdoor
  namespace: casdoor
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: casdoor
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  #EDIT IT: if you don't want to run casdoor in default namespace, please modify this field
  namespace: casdoor
  name: casdoor
  labels:
    app: casdoor
spec:
  #EDIT IT: if you don't use redis, casdoor should not have multiple replicas
  replicas: 1
  serviceName: "casdoor"
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor
          image: casbin/casdoor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            # the mounted directory path in THE CONTAINER
            - mountPath: "/conf"
              name: casdoor-data
            - mountPath: /conf/app.conf
              subPath: app.conf
              name: casdoor-config
          env:       
            - name: RUNNING_IN_DOCKER
              value: "true"
      #if you want to deploy this in real prod env, consider the config map
      volumes:
        - name: casdoor-config
          configMap:
            name: cadoor-config
        - name: casdoor-data
          configMap:
            name: cadoor-data
  volumeClaimTemplates:
  - metadata:
      name: casdoor-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cadoor-config
  namespace: casdoor
data:
  app.conf: |
    driverName = sqlite
    dataSourceName = "file:/conf/casdoor.db?cache=shared"
    dbName = casdoor
```
