### ISSUE TITLE
init_data.json is reloaded when the pod is recreated

### ISSUE THREAD

**Issue by MasonXon** [casdoor/casdoor#3292]
I used casdoor in my program as described [here](https://casdoor.org/docs/deployment/data-initialization/#for-kubernetes), but every time the pod was rebuilt, init_data.json would be reloaded, which would change the user id defined in init_data.json, making it impossible to associate users with my application. 

I used version 1.571.0 before and there was no such problem, all is okay, but [Login page prompt after signup 'invalid captcha provider](https://github.com/casdoor/casdoor/issues/3279).

**Current Version: 1.725.0**

Application:
```shell
'failed to signin: failed to create user,error:failed to create user in db,error:ERROR: duplicate key value violates unique constraint "users_email_key" (SQLSTATE=23505)'
```

Casdoor Database:
<img width="704" alt="image" src="https://github.com/user-attachments/assets/32f7b9a3-f833-4132-b32e-b7b71bf67dc9">
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/47d78a9e-bc4b-4f3a-9281-8b9d7ee25a68">

**Comment by MasonXon** [comment]
I tried switching to the 1.571.0 image and confirmed that everything was ok.

**Comment by hsluoyz** [comment]
@MasonXon which version starts to have the issue you claimed? Or in another way, which PR introduces this issue?

**Comment by MasonXon** [comment]
casdoor:1.725.0

**Comment by hsluoyz** [comment]
@MasonXon you mean this PR: https://github.com/casdoor/casdoor/pull/3269 causes your issue? It's impossible. It only changes frontend JS

**Comment by MasonXon** [comment]
No associated PR, I used `casdoor:1.571.0` before, To fix [https://github.com/casdoor/casdoor/issues/3279](https://github.com/casdoor/casdoor/issues/3279), upgrade to `casdoor:1.725.0`, This problem was found in the current version.

**Comment by MasonXon** [comment]
This should be a new bug.

**Comment by hsluoyz** [comment]
> which version starts to have the issue you claimed? Or in another way, which PR introduces this issue?

I don't have time to do that bi-search thing. This is why I asked it. If you could help on this step, this issue will be solved earlier.

**Comment by MasonXon** [comment]
I don't know which PR introduced this issue, I upgraded directly from 1.571.0 to 1.725.0 to 1.732.0. I only know that your latest version `casdoor:1.732.0` still has this problem. I have mentioned this version many times above. 
Because the speed at which you release images is really terrifying, I can't easily locate which version or PR introduced this problem.

**Comment by MasonXon** [comment]
I have located the problem. This problem occurred in the 1.607.0 tag, and 1.606.0 is normal.

Please see: [feat: fix bug that fails to import built-in org via init_data.json](https://github.com/casdoor/casdoor/compare/v1.606.0...v1.607.0)

**Comment by MasonXon** [comment]
@hsluoyz

**Comment by hsluoyz** [comment]
@MasonXon thanks for locating the problem! I saw the related PR is this one: https://github.com/casdoor/casdoor/pull/2922

@dacongda can you help on this?

**Comment by dacongda** [comment]
can you post your app.conf? you should set `initDataFile = "./init_data.json"` equal to `initDataFile = ""` or some thing after you successfully migrate data from `init_data.json`, or you can just remove `init_data.json`

**Comment by MasonXon** [comment]
This is my casdoor config file.
```toml
appname = casdoor
httpport = 8000
runmode = prod
copyrequestbody = true
driverName = postgres
dataSourceName = "user=casdoor password=WWpaaE5tRXlOalEzT1RjNE5HVmhaZz09 host=csghub-postgresql port=5432 sslmode=disable dbname=casdoor"
dbName =
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
origin =
originFrontend =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
enableGzip = true
ldapServerPort = 389
radiusServerPort = 1812
radiusSecret = "secret"
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
logConfig = {"filename": "logs/casdoor.log", "maxdays":99999, "perm":"0770"}
initDataFile = "/conf/init_data.json"
frontendBaseDir = "../casdoor"
```

Above config file defined in kubernetes configMap, this is for casdoor deployment, so if I recreate casdoor pod, should I recreate configMap to empty `initDataFile` parameter ??? This seems inappropriate, Even if it is. not in k8s, this operation is unreasonable. and everything is normal in 1.606.0 and previous versions. I've seen the PR https://github.com/casdoor/casdoor/issues/2920, and it seems like it doesn't determine whether the init data has been initialzied, always reinit?
