### ISSUE TITLE
panic: unable to open database file: out of memory

### ISSUE THREAD

**Issue by droplet-js** [casdoor/casdoor#3466]
docker-compose.yaml

```yaml
services:
  casdoor:
    container_name: casdoor
    image: casbin/casdoor:v1.783.0
    restart: unless-stopped
    hostname: casdoor
    # ports:
    #   - 8000
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../dev-ops-repo/casdoor/conf:/conf
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
      - driverName=sqlite
      - dataSourceName=file:/conf/casdoor.db?cache=shared
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.casdoor.loadbalancer.server.port=8000"
      - "traefik.http.routers.casdoor.service=casdoor"
      - "traefik.http.routers.casdoor.rule=Host(`casdoor.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.casdoor.entrypoints=websecure"
```

it work well on mac, not work well for centos.

```log
panic: unable to open database file: out of memory (14)

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Ormer).createTable(0xc000968480)
        /go/src/casdoor/object/ormer.go:293 +0xaa5
github.com/casdoor/casdoor/object.CreateTables()
        /go/src/casdoor/object/ormer.go:114 +0x3a
main.main()
        /go/src/casdoor/main.go:36 +0x35
panic: unable to open database file: out of memory (14)
```

i have found, it not auto create casdoor.db on centos
