### ISSUE TITLE
[Bug] PostgreSQL connection error when using `dataSourceName` with key-value format in `app.conf`

### ISSUE THREAD

**Issue by iCasture** [casdoor/casdoor#3762]
I’m using the official `casbin/casdoor` Docker image with a PostgreSQL database.

According to the official documentation [Server Installation - PostgreSQL](https://casdoor.org/docs/basic/server-installation#postgresql), I configured `conf/app.conf` as follows (note: the casdoor database has already been created in advance, and the host casdoor-db-pg is accessible from within the Casdoor container):

```conf
driverName = postgres
dataSourceName = user=fooName password=fooPasswd host=casdoor-db-pg port=5432 sslmode=disable dbname=casdoor
dbName = casdoor
```

However, after starting the Docker container, I get the following error:

```text
panic: pq: database "fooName" does not exist

goroutine 1 [running]:
github.com/casdoor/casdoor/object.InitAdapter()
	/go/src/casdoor/object/ormer.go:91 +0x204
main.main()
	/go/src/casdoor/main.go:36 +0x24
panic: pq: database "fooName" does not exist

goroutine 1 [running]:
github.com/casdoor/casdoor/object.InitAdapter()
	/go/src/casdoor/object/ormer.go:91 +0x204
main.main()
	/go/src/casdoor/main.go:36 +0x24
panic: pq: database "fooName" does not exist

goroutine 1 [running]:
github.com/casdoor/casdoor/object.InitAdapter()
	/go/src/casdoor/object/ormer.go:91 +0x204
main.main()
	/go/src/casdoor/main.go:36 +0x24
panic: pq: database "fooName" does not exist

goroutine 1 [running]:
github.com/casdoor/casdoor/object.InitAdapter()
	/go/src/casdoor/object/ormer.go:91 +0x204
main.main()
	/go/src/casdoor/main.go:36 +0x24
panic: pq: database "fooName" does not exist

goroutine 1 [running]:
github.com/casdoor/casdoor/object.InitAdapter()
	/go/src/casdoor/object/ormer.go:91 +0x204
main.main()
	/go/src/casdoor/main.go:36 +0x24
```

It looks like Casdoor is trying to connect to a database named `fooName`, instead of the database `casdoor` specified by `dbname=casdoor` in `dataSourceName`.

Interestingly, if I change `conf/app.conf` to use the URL-style connection string:

```conf
driverName = postgres
dataSourceName = postgres://fooName:fooPasswd@casdoor-db-pg:5432/casdoor?sslmode=disable
dbName = casdoor
```

then Casdoor starts successfully.

Is this a bug in Casdoor? Or is there an issue with the example configuration provided in the official documentation?

**Comment by dacongda** [comment]
```text
driverName = postgres
dataSourceName = user=fooName password=fooPasswd host=casdoor-db-pg port=5432 sslmode=disable dbname=casdoor
dbName = casdoor <= Replace this with dbName = 
```

you can try connect to pg like this, It seems that this is a fault in db?

**Comment by iCasture** [comment]
@dacongda 

```conf
driverName = postgres
dataSourceName = "user=fooName password=fooPasswd host=casdoor-db-pg port=5432 sslmode=disable dbname=casdoor"
dbName =
```

```conf
driverName = postgres
dataSourceName = "user=fooName password=fooPasswd host=casdoor-db-pg port=5432 sslmode=disable dbname=casdoor "
dbName =
```

```conf
driverName = postgres
dataSourceName = user=fooName password=fooPasswd host=casdoor-db-pg port=5432 sslmode=disable dbname=casdoor
dbName =
```

None of the configurations above work; they all result in the following error:
`panic: pq: database "fooName" does not exist`.

Here, `fooName` refers to the PostgreSQL username specified by the `user` parameter in `dataSourceName`, rather than the database name (`dbname`). I don't know why Casdoor keeps trying to connect to a database named `fooName`.

In addition, the following configuration doesn’t work either, resulting in `panic: pq: syntax error at or near ";"`:

```conf
driverName = postgres
dataSourceName = postgres://fooName:fooPasswd@casdoor-db-pg:5432/casdoor?sslmode=disable
dbName =
```

The only configuration that works is this one:

```conf
driverName = postgres
dataSourceName = postgres://fooName:fooPasswd@casdoor-db-pg:5432/casdoor?sslmode=disable
dbName = casdoor
```

**Comment by dacongda** [comment]
but I did successfully connect to pg with 

![Image](https://github.com/user-attachments/assets/83aca338-e8c9-4c89-90e8-41069b13a2a8)

and 

![Image](https://github.com/user-attachments/assets/e269502b-efe9-4bac-861d-38b170cfdeab)

**Comment by dacongda** [comment]
![Image](https://github.com/user-attachments/assets/66c918ca-29b9-42ef-993f-190fb0196010)

conf like this also works to me 

![Image](https://github.com/user-attachments/assets/e8ce7c00-b4c2-4a4b-95d3-d2abc1da3734)

**Comment by iCasture** [comment]
@dacongda 

The PostgreSQL version is `postgres:17.4`, system version: `macOS Sequoia 15.4.1 arm64`.

Below is the complete `compose.yaml` file:

```yaml
services:
  casdoor:
    image: casbin/casdoor:v1.901.0
    container_name: casdoor
    hostname: casdoor
    environment:
      RUNNING_IN_DOCKER: "true"
    ports:
      - "30000:8000"
    volumes:
      - ./conf/app.conf:/conf/app.conf
    depends_on:
      casdoor-db-pg:
        condition: service_healthy
    entrypoint: /bin/sh -c './server --createDatabase=true'
    restart: unless-stopped
  casdoor-db-pg:
    image: postgres:17.4
    container_name: casdoor-db-pg
    hostname: casdoor-db-pg
    expose:
      - "5432"
    environment:
      TZ: "Asia/Shanghai"
      PGTZ: "Asia/Shanghai"
      POSTGRES_USER_FILE: "/run/secrets/pg-user"
      POSTGRES_PASSWORD_FILE: "/run/secrets/pg-passwd"
      POSTGRES_DB_FILE: "/run/secrets/pg-db"
    volumes:
      - ./casdoor-pg-data:/var/lib/postgresql/data
    secrets:
      - pg-user
      - pg-passwd
      - pg-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$(awk '{$1=$1} NF' /run/secrets/pg-user)\""]
      interval: 1s
      timeout: 5s
      retries: 25
    restart: unless-stopped
secrets:
  pg-user:
    file: ./secrets/default-pg-user.key
  pg-passwd:
    file: ./secrets/default-pg-pass.key
  pg-db:
    file: ./secrets/default-pg-db.key
```

And `app.conf`:

```conf
appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = postgres
dataSourceName = user=fooName password=fooPasswd host=casdoor-db-pg port=5432 sslmode=disable dbname=casdoor
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
isUsernameLowered = false
origin =
originFrontend =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
enableErrorMask = false
enableGzip = true
inactiveTimeoutMinutes =
ldapServerPort = 389
ldapsCertId = ""
ldapsServerPort = 636
radiusServerPort = 1812
radiusDefaultOrganization = "built-in"
radiusSecret = "secret"
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
logConfig = {"filename": "logs/casdoor.log", "maxdays":99999, "perm":"0770"}
initDataNewOnly = false
initDataFile = "./init_data.json"
frontendBaseDir = "../cc_0"
```

I’m not sure why the instance I started always tries to connect to the database specified in `user` instead of the one specified in `dbname`.

Maybe I should just use the connection string in this format: `postgres://USER:PASSWD@HOST:PORT/DBNAME?sslmode=disable`.
