### ISSUE TITLE
Enhancement: Add Trivy Vulnerability Scanning to the Pipeline

### ISSUE THREAD

**Issue by guimoreirar** [casdoor/casdoor#3849]
It could be a good idea to add a Trivy security scan step to the CI pipeline. This would help check for vulnerabilities in Docker images or dependencies before releasing. By configuring the scan to fail on detected vulnerabilities (exit-code: 1), it would prevent publishing containers with known security issues

like this:

```
      - name: Scan casdoor image with Trivy
        if: github.repository == 'casdoor/casdoor' && github.event_name == 'push' && steps.should_push.outputs.push=='true'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'casbin/casdoor:${{steps.get-current-tag.outputs.tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Push All In One Version to Docker Hub
        uses: docker/build-push-action@v3
        if: github.repository == 'casdoor/casdoor' && github.event_name == 'push' && steps.should_push.outputs.push=='true'
        with:
          context: .
          target: ALLINONE
          platforms: linux/amd64,linux/arm64
          push: true
          tags: casbin/casdoor-all-in-one:${{steps.get-current-tag.outputs.tag }},casbin/casdoor-all-in-one:latest

      - name: Scan casdoor-all-in-one image with Trivy
        if: github.repository == 'casdoor/casdoor' && github.event_name == 'push' && steps.should_push.outputs.push=='true'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'casbin/casdoor-all-in-one:${{steps.get-current-tag.outputs.tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
```
