### ISSUE TITLE
BUG: updating organization name is not reflected in entries using it and breaks ui

### ISSUE THREAD

**Issue by 8byr0** [casdoor/casdoor#391]
I was playing around with casdoor and wanted to rename `built-in` organization. After doing so the frontend was no longer loaded, failing with a javascript error raised in the console:
```
TypeError: Cannot read properties of null (reading 'displayName')
    at n.value (main.c9d95680.chunk.js:1)
    at Uo (2.8e478ed0.chunk.js:2)
    at Vo (2.8e478ed0.chunk.js:2)
    at Wl (2.8e478ed0.chunk.js:2)
    at Ts (2.8e478ed0.chunk.js:2)
    at ws (2.8e478ed0.chunk.js:2)
    at ks (2.8e478ed0.chunk.js:2)
    at vs (2.8e478ed0.chunk.js:2)
    at 2.8e478ed0.chunk.js:2
    at t.unstable_runWithPriority (2.8e478ed0.chunk.js:2)
``` 

I checked db and noticed that application table entries still add `built-in` as `organization` value.

To reproduce: 
1. start a fresh install using docker-compose below
2. Login with admin/123
3. Go to organizations and rename `built-in` to `whatever`
4. Open http://localhost:8000 in a new tab
5. Check JS console

Relevant docker-compose.yml:
```yaml
# docker-compose.yml 
version: "3.1"
services:
  casdoor:
    image: casbin/casdoor
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - casdb
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/conf/
  casdb:
    container_name: casdb
    restart: unless-stopped
    image: mariadb:10
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./dbdata:/var/lib/mysql
```
App conf:
```conf
# conf/app.conf
appname = casdoor
httpport = 8000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = mysql
dataSourceName = root:123456@tcp(casdb:3306)/
dbName = casdoor
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
httpProxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin = "https://door.casbin.com"
```
 
I did not investigate further, `organization` may be used the same way in other tables.
This field should have a fk constraint on `organization.name`
