### ISSUE TITLE
Doc: OIDC for Minio: Unable to set identity_openid - connection refused

### ISSUE THREAD

**Issue by tetra12** [casdoor/casdoor#639]
I'm trying to setup an OIDC for Minio following [this](https://casdoor.org/docs/integration/minio). I use three containers to implement the system. MySQL is run separately and standalone. Casdoor and Minio are set up using [this](https://gist.github.com/tetra12/308bebea586b25c327b64407c9d53b93).

When I do `docker-compose up`, I have all three containers up&working. I'm able to log into Casdoor and Minio (using internal auth).

However, when I try to add OIDC using `mc` locally with this:
`mc admin config set sdk identity_openid config_url='http://127.0.0.1:8000/.well-known/openid-configuration' client_id=d598b9d3073e4ef1e5bb client_secret=7ca91140c38d8427f46a769aaec882c4e17ee1e6 claim_name='tag'`

I'm getting the following:
```bash
mmc: <ERROR> Unable to set 'identity_openid config_url=http://127.0.0.1:8000/.well-known/openid-configuration 
client_id=xxx client_secret=yyy claim_name=tag' to server. Get "http://127.0.0.1:8000/.well-known/openid-configuration": dial tcp 127.0.0.1:8000: connect: connection refused.
```

**Comment by hsluoyz** [comment]
@Steve0x2a

**Comment by Steve0x2a** [comment]
` Get "http://127.0.0.1:8000/.well-known/openid-configuration": dial tcp 127.0.0.1:8000: connect: connection refused.` 
Are you able to access `http://127.0.0.1:8000/.well-known/openid-configuration` properly on your browser?

**Comment by tetra12** [comment]
@Steve0x2a Yes, I can.

1. As I said, I have all three apps in containers. I can access Casdoor and Minio properly and I can access OIDC config with `curl http://127.0.0.1:8000/.well-known/openid-configuration` from my host

2. I run `mc` locally, not in a container. This may be a cause of an issue. Feel free to give an example if you find issues in my compose file

3. I also tried to setup OIDC related envs in a `docker-compose.yml` with the following:
```yaml
s3:
    image: quay.io/minio/minio:latest
    container_name: s3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /mnt/s3:/data

    environment:
      - MINIO_ROOT_USER=$S3_ROOT_USER
      - MINIO_ROOT_PASSWORD=$S3_ROOT_PASSWORD
      - MINIO_IDENTITY_OPENID_CONFIG_URL='127.0.0.1:8000/.well-known/openid-configuration'
      - MINIO_IDENTITY_OPENID_CLIENT_ID=$SDK_OIDC_CLIENT_ID
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET=$SDK_OIDC_CLIENT_SECRET
      - MINIO_IDENTITY_OPENID_CLAIM_NAME=tag
     ...
```
This gave a similar issue with access to `127.0.0.1:8000/.well-known/openid-configuration` during a container start.

Let me know if you need more info from me
