### ISSUE TITLE
Cannot connect to Postgres with Docker Compose

### ISSUE THREAD

**Issue by tombrouwer** [casdoor/casdoor#675]
Hi,

I'm trying to set up Casdoor. I want to use a Postgres database later in production. I've now created a Docker compose file, and an app.conf file, but I keep running into issues.

If I set the settings as described here: https://casdoor.org/docs/basic/server-installation#via-ini-file
```
driverName = postgres
dataSourceName = "user=postgres password=postgrespassword sslmode=disable dbname="
dbName = auth_server
```

Then I get the error: `panic: dbname is empty`

If I change it to:
```
driverName = postgres
dataSourceName = "user=postgres password=postgrespassword sslmode=disable dbname=auth_server"
dbName = auth_server
```

Then I get the error: `panic: dial tcp 127.0.0.1:5432: connect: connection refused`

My app.conf:
```
appname = AuthServer
httpport = 8000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = postgres
dataSourceName = "user=postgres password=postgrespassword sslmode=disable dbname="
dbName = auth_server
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider = 
isCloudIntranet = false
authState = "casdoor"
sock5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin =
```

My docker-compose.yaml:
```
version: "3.6"

services:
  casdoor:
    image: casbin/casdoor:v1.43.0
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./casdoor/conf:/conf/

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: auth_server
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
```

**Comment by hsluoyz** [comment]
@tombrouwer does Postgres work without Docker? (run Go backend in the hsot)

**Comment by hsluoyz** [comment]
@ComradeProgrammer

**Comment by adamwoolhether** [comment]
just chiming in to say the postgres driver is commented out in adapter.go... we can specify a non-mysql db when this is commented out???

**Comment by adamwoolhether** [comment]
@tombrouwer here's how i got it working:
In `adapter.go`, uncomment the pq adapter and comment out mysql:
```
	// _ "github.com/denisenkom/go-mssqldb" // db = mssql
	// _ "github.com/go-sql-driver/mysql" // db = mysql
	_ "github.com/lib/pq" // db = postgres
```
In the config file, include the db name in `dataSourceName`  field and leave `dbName` field blank, contrary to the documentation, like so:
```
dataSourceName = "user=postgresuser password=p@ssword host=xx.xx.xxx.xxx port=1234 sslmode=disable **dbname=casdoor**"
dbName =
```

you also have to manually create the db before running it.

**Comment by tombrouwer** [comment]
I got it working too. Using the docker as above. However, I had to change the configuration slightly. The documentation isn't really clear on how to set the "dataSourceName". I also searched XORM but didn't get any clearer either.

The documentation says you should end with dbname= but that doesn't seem necessary. See: https://casdoor.org/docs/basic/server-installation

I removed "dbName" and changed the dataSourceName:

```
appname = AuthServer
httpport = 8000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = postgres
dataSourceName = "user=postgres host=postgres port=5432 password=postgrespassword sslmode=disable dbname=auth_server"
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider = 
isCloudIntranet = false
authState = "casdoor"
sock5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin =
```

I can now continue playing around. And find out how beautiful the software is that you make. Thanks!

**Comment by hsluoyz** [comment]
@tombrouwer @adamwoolhether hi, are you willing to improve our docs to avoid more people encountering your problem? https://github.com/casdoor/casdoor-website/issues/181

**Comment by cold-runner** [comment]
I am having the same problem, when using `docker compose`, if both `MySQL`and `casdoor` are running as containers, then `casdoor` will be denied access when connecting to `MySQL`. So is there any way to allow containerized `casdoor` to connect to containerized `MySQL`?

**Comment by hsluoyz** [comment]
@cold-runner use the all-in-one image: https://casdoor.org/docs/basic/try-with-docker#option-1-use-the-toy-database

**Comment by cold-runner** [comment]
What if it's a production environment, I want to use my own database. I configured `docker-compose.yml` according to the [https://casdoor.org/docs/basic/try-with-docker/#option-3-try-with-docker-compose](https://casdoor.org/docs/basic/try-with-docker/#option-3-try-with-docker-compose), but `casdoor` still can't connect to `MySQL`
```
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    volumes:
      - ./deploy/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=casdoor
      - MYSQL_ROOT_PASSWORD=123456

  casdoor:
    image: casbin/casdoor
    ports:
      - "8000:8000"
    environment:
      - RUNNING_IN_DOCKER = true
    volumes:
      - ./deploy/casdoor:/conf
```
The contents of `app.conf` are as follows
```
appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = mysql
dataSourceName = root:123456@tcp(localhost:3306)/
dbName = casdoor
tableNamePrefix = 
showSql = false
redisEndpoint = 
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
isUsernameLowered = false
origin =
originFrontend =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
enableGzip = true
ldapServerPort = 389
radiusServerPort = 1812
radiusSecret = "secret"
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
logConfig = {"filename": "logs/casdoor.log", "maxdays":99999, "perm":"0770"}
initDataFile = "./init_data.json"
frontendBaseDir = "../casdoor"
```
