### ISSUE TITLE
Can't login with admin/123 use latest docker image version(casbin/casdoor v1.71.0)

### ISSUE THREAD

**Issue by jmluang** [casdoor/casdoor#901]
![2022-07-20 01 04 15](https://user-images.githubusercontent.com/11557732/179808386-de2aabed-884b-4ac2-8192-73f580b5ebde.png)

v1.71.0  can't login :

msg: Unexpected end of JSON input

similar with #876 , But it happens on the backend

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by leo220yuyaodog** [comment]
@jmluang I test version v1.71.0, it work well.  I cannot reproduce the issue.

**Comment by jmluang** [comment]
@leo220yuyaodog 
```
version: '3.1'
services:
  casdoor:
    image: casbin/casdoor:v1.71.0
    container_name: casdoor
    restart: always
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8000:8000"
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/conf/
```
```
conf/app.conf
driverName = mysql
dataSourceName = username:password@tcp(localhost:3306)/
dbName = casdoor
```
 i'm running in docker, can you try my conf? I have reproduce this issue on different servers.
